[advisories]
yanked = "warn"
unmaintained = "all"
unsound = "workspace"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
